# http://localhost:3000/openapi.yml

openapi: 3.0.1
info:
  title: API ERP - Ordem de Servico
  version: 1.0.0
  description: |
    API para gerenciamento de ordens de servico.
    Permite listar e criar ordens de servico.

servers:
  - url: http://localhost:3000
    description: Servidor local de desenvolvimento

paths:
  /ordem_servicos:
    get:
      summary: Lista todas as ordens de servico
      description: Retorna todas as ordens ordenadas da mais recente para a mais antiga.
      tags:
        - Ordem de Servico
      responses:
        '200':
          description: Lista de ordens de servico
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrdemServico'
    post:
      summary: Cria uma nova ordem de servico
      description: Cria um novo registro de ordem de servico.
      tags:
        - Ordem de Servico
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrdemServicoCreate'
            example:
              ordem_servico:
                nome_cliente: "Juan Roberto"
                data_entrada: "2025-08-24"
                data_saida: "2025-08-28"
                status: "Em andamento"
      responses:
        '201':
          description: Ordem de servico criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrdemServico'
        '422':
          description: Erro de validacao
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
              example:
                errors:
                  - "Nome do cliente nao pode ficar em branco"

components:
  schemas:
    OrdemServico:
      type: object
      properties:
        id:
          type: integer
          example: 1
        numero_os:
          type: string
          example: "OS-0001"
        nome_cliente:
          type: string
          example: "Juan Roberto"
        data_entrada:
          type: string
          format: date
          example: "2025-08-24"
        data_saida:
          type: string
          format: date
          example: "2025-08-28"
        status:
          type: string
          example: "Em andamento"
        created_at:
          type: string
          format: date-time
          example: "2025-08-24T10:20:30Z"
        updated_at:
          type: string
          format: date-time
          example: "2025-08-24T10:20:30Z"
    OrdemServicoCreate:
      type: object
      properties:
        ordem_servico:
          type: object
          properties:
            nome_cliente:
              type: string
            data_entrada:
              type: string
              format: date
            data_saida:
              type: string
              format: date
            status:
              type: string
          required:
            - nome_cliente
            - data_entrada
            - status
