openapi: 3.0.1
info:
  title: API ERP - Ordem de Serviço
  version: 1.0.0
  description: API para gerenciamento de ordens de serviço. Permite listar e criar ordens de serviço.

servers:
  - url: http://localhost:3000
    description: Servidor local de desenvolvimento

paths:
  /ordem_de_servicos:
    get:
      summary: Lista todas as ordens de serviço
      description: Retorna todas as ordens ordenadas da mais recente para a mais antiga.
      tags:
        - Ordem de Serviço
      responses:
        '200':
          description: Lista de ordens de serviço
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrdemServico'
    post:
      summary: Cria uma nova ordem de serviço
      description: Cria um novo registro de ordem de serviço.
      tags:
        - Ordem de Serviço
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrdemServicoCreate'
            example:
              ordem_servico:
                nome_cliente: "Juan Roberto"
                data_entrada: "2025-08-24"
                data_saida: "2025-08-28"
                status: "aguardando_checklist"
      responses:
        '201':
          description: Ordem de serviço criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrdemServico'
        '422':
          description: Erro de validação
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
              example:
                errors:
                  - "Nome do cliente não pode ficar em branco"

components:
  schemas:
    OrdemServico:
      type: object
      properties:
        id:
          type: integer
          example: 1
        numero_os:
          type: string
          example: "OS-0001"
        nome_cliente:
          type: string
          example: "Juan Roberto"
        data_entrada:
          type: string
          format: date
          example: "2025-08-24"
        data_saida:
          type: string
          format: date
          example: "2025-08-28"
        status:
          type: string
          enum:
            - aguardando_checklist
            - aguardando_orcamento
            - em_andamento
            - finalizada
          example: "em_andamento"
        created_at:
          type: string
          format: date-time
          example: "2025-08-24T10:20:30Z"
        updated_at:
          type: string
          format: date-time
          example: "2025-08-24T10:20:30Z"

    OrdemServicoCreate:
      type: object
      properties:
        ordem_servico:
          type: object
          properties:
            nome_cliente:
              type: string
            data_entrada:
              type: string
              format: date
            data_saida:
              type: string
              format: date
            status:
              type: string
              enum:
                - aguardando_checklist
                - aguardando_orcamento
                - em_andamento
                - finalizada
          required:
            - nome_cliente
            - data_entrada
            - status
